# Generated by Django 2.2 on 2019-09-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='event', to='eventFinderApp.Category'),
        ),
    ]
