# Generated by Django 2.2 on 2019-09-15 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventFinderApp', '0005_auto_20190914_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hosting_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
